### ISSUE TITLE
"type 'double' is not a subtype of type 'int'" calling Color.css('rgba(27,31,35,0.1)')

### ISSUE THREAD

**Issue by DanTup** [dart-lang/csslib#88]
Running in Dart 2.2, this code:

```dart
final a = Color.css('rgba(27,31,35,0.1)');
```

throws:

```
type 'double' is not a subtype of type 'int'
#0      Color._convertCssToArgb 
../…/src/property.dart:281
#1      new Color.css 
../…/src/property.dart:92
#2      main 
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Presumably it's because the args are parsed as doubles (`args.add(double.parse(param));`) but the signature of `convertToHexString` expects `int`s for the first three params.

**Comment by Schnurber** [comment]
Same problem!
